import { Box, Code, Flex, Grid, Heading, Link, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <Box px={2}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        as="main"
        display="flex"
        alignItems="center"
        justifyContent="center"
        flexDir="column"
        minHeight="100vh"
        py={4}
      >
        <Heading as="h1" fontSize="6xl">
          Welcome to{' '}
          <Link variant="primary" href="https://nextjs.org">
            Next.js!
          </Link>
        </Heading>

        <Text fontSize="xl" my={10}>
          Get started by editing{' '}
          <Code px={4} py={2} borderRadius={4}>
            pages/index.tsx
          </Code>
        </Text>

        <Flex
          flexWrap="wrap"
          alignItems="center"
          justifyContent="center"
          maxWidth="800px"
        >
          <Link
            href="https://nextjs.org/docs"
            m={4}
            p={6}
            _hover={{
              textDecoration: 'none',
              color: 'primary.400',
              borderColor: 'primary.400',
            }}
            maxWidth="300px"
            borderRadius="md"
            border="1px"
            borderColor="gray.200"
          >
            <Heading as="h2" fontSize="2xl" fontWeight="normal" mb={4}>
              Documentation &rarr;
            </Heading>
            <Text fontSize="xl">
              Find in-depth information about Next.js features and API.
            </Text>
          </Link>

          <Link
            href="https://nextjs.org/learn"
            m={4}
            p={6}
            _hover={{
              textDecoration: 'none',
              color: 'primary.400',
              borderColor: 'primary.400',
            }}
            maxWidth="300px"
            borderRadius="md"
            border="1px"
            borderColor="gray.200"
          >
            <Heading as="h2" fontSize="2xl" fontWeight="normal" mb={4}>
              Learn &rarr;
            </Heading>
            <Text fontSize="xl">
              Learn about Next.js in an interactive course with quizzes!
            </Text>
          </Link>

          <Link
            href="https://github.com/vercel/next.js/tree/master/examples"
            m={4}
            p={6}
            _hover={{
              textDecoration: 'none',
              color: 'primary.400',
              borderColor: 'primary.400',
            }}
            maxWidth="300px"
            borderRadius="md"
            border="1px"
            borderColor="gray.200"
          >
            <Heading as="h2" fontSize="2xl" fontWeight="normal" mb={4}>
              Examples &rarr;
            </Heading>
            <Text fontSize="xl">
              Discover and deploy boilerplate example Next.js projects.
            </Text>
          </Link>

          <Link
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            m={4}
            p={6}
            _hover={{
              textDecoration: 'none',
              color: 'primary.400',
              borderColor: 'primary.400',
            }}
            maxWidth="300px"
            borderRadius="md"
            border="1px"
            borderColor="gray.200"
          >
            <Heading as="h2" fontSize="2xl" fontWeight="normal" mb={4}>
              Deploy &rarr;
            </Heading>
            <Text fontSize="xl">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Text>
          </Link>
        </Flex>
      </Box>

      <Box
        as="footer"
        display="flex"
        justifyContent="center"
        alignItems="center"
        py={8}
        borderTop="1px"
        borderColor="gray.200"
      >
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          isExternal
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </Box>
    </Box>
  );
};

export default Home;
